config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views


urlpatterns =[
    path('', base_views.index, name='index'),    # '/' 에 해당되는 path
    path("admin/", admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls'))
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),                          # 목록 보기
    path('<int:question_id>/', base_views.detail, name='detail'),       # 상세 보기

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField('제목', max_length=200, 
                               help_text='질문의 제목을 한 줄로 작성하세요.')
    content = models.TextField('내용', help_text='질문의 내용을 상세히 작성하세요.')
    create_date = models.DateTimeField('생성일')
    modify_date = models.DateTimeField(null=True, blank=True)

    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return f'{self.id} {self.subject}'

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField('답변 내용')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        # return self.question
        return f'{self.id} {self.subject}'

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # User.comment_set
    content = models.TextField('댓글내용')
    create_date = models.DateTimeField('생성일')
    modify_date = models.DateTimeField('수정일', null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    # Question.comment_set

    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
    # Answer.comment_set

    def __str__(self):
        return self.content

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        widgets = {
            'subject': forms.TextInput(attrs={'placeholder': '제목을 입력하세요.'}),
            'content': forms.Textarea(attrs={'placeholder': '내용을 입력하세요.'}),
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글 내용'
        }

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question, Answer
from ..forms import AnswerForm



@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question  # Foreignkey
            answer.save()
            # 앵커 #answer_5 추가
            url = resolve_url('pybo:detail', question_id=question_id)

            # 아래 2 코드중 어느 코드를 쓰던 된다.
            return redirect(f'{url}#answer_{answer.id}')
            # url = url + f'#answer_{answer.id}'
            # return redirect(url)
            
    else: # get 방식.
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            url = resolve_url('pybo:detail', question_id=answer.question.id)

            url = url + f'#answer_{answer.id}'
            return redirect(url)
    else: #GET처리
        form = AnswerForm(instance=answer)

    context = {'answer': answer, 'form': form}

    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.db.models import Q, Count



def index(request):
    """
    pybo 목록출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')    # 정렬 기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:   # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회
    # question_list = Question.objects.order_by('-create_date') #전체 목록
    # question_list = Question.objects.order_by('-author__username') # 이름순으로 검색

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |      # 제목 검색
            Q(content__icontains=kw) |      # 내용 검색
            Q(author__username__icontains=kw) |     # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)   # 답글 글쓴이 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)    # 페이지당 10개씩 보여주기. question_list => 전체목록
    page_obj = paginator.get_page(page)

    context = {
        'kw': kw,
        'page': page,
        'so': so,
        'question_list': page_obj
        }

    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)


    # question.answer_set.create(content=request.POST.get('content'),
    #             create_date=timezone.now())

    # return redirect('pybo:detail', question_id=question_id)
    # print(request.method)
    # print(request.GET)      # dict
    # print(request.POST)     # dict

    # content = request.POST['content']           # 1) 키가 없으면, 예외 발생
    # print('[content]', content)

    # content = request.POST.get('content', '')       # 2) 키가 없으면, None 리턴


    # print('get(content)', content)

pybo/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..forms import CommentForm
from ..models import Question, Answer, Comment



@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            url = resolve_url('pybo:detail', question_id=question_id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)



@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            url = resolve_url('pybo:detail', question_id=comment.question_id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}

    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제 권한이 없습니다.')
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.question.id)



@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            url = resolve_url('pybo:detail', question_id=comment.answer.question.id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답글 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            url = resolve_url('pybo:detail', question_id=comment.answer.question.id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}

    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제 권한이 없습니다.')
    else:
        comment.delete()

    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question





@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':    # submit을 통한 POST 요청
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:                           # GET 요청
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)




@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question_id)

    if request.method == "POST":
        # 질문 수정을 위해 값 덮어쓰기
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()   # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        # 질문 수정 화면에 기존 제목, 내용 반영
        form = QuestionForm(instance=question)

    context = {'form':form}

    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from ..models import Question, Answer

@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    pybo 질문 추천 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question_id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답글 추천 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_create_form.html
<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
  {% csrf_token %}
  {% if form.errors %}
    <div class="alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
          <strong>{{ field.label }}</strong>
          {{ field.error }}
        {% endif %}
      {% endfor %}
    </div>
  {% endif %}
  <div class="form-group">
    <textarea {% if not user.is_authenticated %} disabled="disabled" {% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
  </div>
  <input type="submit" value="답변등록" class="btn btn-outline-primary">
</form>

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <form method="POST" class="post-form">
    {% csrf_token %}

    {% bootstrap_form form %}

    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>

{% endblock content %}

templates/pybo/answer_list.html
{% load pybo_filter %}

<!-- 댓글 목록 -->
<h5 class="border-bottom my-3 py-2">
  <i class="fa-solid fa-comments"></i>
  {{ question.answer_set.count }}개의 답변이 있습니다.
</h5>

{% for answer in question.answer_set.all %}
  <a name="answer_{{answer.id}}"></a>
  <div class="row my-3">
    <div class="col-1">
      <!-- 추천 영역 -->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
      <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <!-- 답변 영역 -->

      <div class="card">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
          <div class="d-flex justify-content-end">
            <!-- d-flex => 플렉스 속성을 주고, justify-content-end => 오른쪽 끝으로 정렬한다 -->
            {% if answer.modify_date %}
              <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">최근 수정일</div>
                <div>{{ answer.modify_date }}</div>
              </div>
            {% endif %}
            <div class="badge badge-info p-2">
              <i class="fa-regular fa-clock"></i>
              {{ answer.create_date }}
            </div>

          </div>

          {% if request.user == answer.author %}
            <div class="my-3">
              <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
            </div>
          {% endif %}

          <!--답변에 대한 댓글-->
          {% include 'pybo/comment_answer.html' %}

        </div>
      </div>
    </div>
  </div>
{% endfor %}

templates/pybo/comment_answer.html
{% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="cark-body">

      {% if answer.comment_set.count > 0 %}
        <a name="comment_{{comment.id}}"></a>
        <div class="mt-3">
          {% for comment in answer.comment_set.all %}
            <div class="comment py-2 text-muted">
              <span style="white-space: pre-line;">
                {{ comment.content }}
              </span>
              <span>
                -
                {{ comment.author }},
                {{ coment.create_date }}
                {% if comment.modify_date %}
                  (수정:{{ comment.modify_date }})
                {% endif %}
              </span>
              {% if request.user == comment.author %}
                <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>
                <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
              {% endif %}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small">
      <small>댓글 추가 ...</small>
    </a>
  </div>

{% endfor %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 등록하기</h5>
    <form method="post" class="post-form my-3">
      {% csrf_token %}

      {% bootstrap_form form %}

      <button type="submit" class="btn btn-primary">
        <i class="fa-solid fa-check"></i>
        저장하기
      </button>
    </form>
  </div>
{% endblock content %}

templates/pybo/comment_question.html
{% comment %} 질문 댓글 Start {% endcomment %}
{% if question.comment_set.count > 0 %}
  <div class="mt-3">
    {% for comment in question.comment_set.all %}
      <div class="comment py-2 text-muted">
        <span style="white-space: pre-line;">{{ comment.content }}</span>
        <span>
          <img class="avatar" src="https://randomuser.me/api/portraits/men/{{comment.author.id}}.jpg"/>
          {{ comment.author }},
          {{ comment.create_date }}
          {% if comment.modify_date %}
            (수정:{{ comment.modify_date }})
          {% endif %}
        </span>
        {% if request.user == comment.author %}
          <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">
            <i class="fa-regular fa-pen-to-square"></i>
            수정
          </a>
          <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">
            <i class="fa-regular fa-trash-can"></i>
            삭제
          </a>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endif %}
<div>
  <a href="{% url 'pybo:comment_create_question' question.id %}" class="small">
    <small><i class="fa-solid fa-plus"></i>댓글 추가 ..</small>
  </a>
</div>
{% comment %} 질문 댓글 End {% endcomment %}

templates/pybo/question_detail.html
{% extends 'base.html' %}

{% load pybo_filter %}

{% block content %}
  <!-- 사용자오류 표시 -->
  {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
      {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
          <li>{{ message.message }}</li>
        </ul>
      {% endfor %}
    </div>
  {% endif %}
  
  <h2 class="border-bottom py-2 text-primary">
    <i class="fa-solid fa-question"></i>
    {{ question.subject }}
  </h2>

  <div class="row my-3">
    <div class="col-1">
      <!-- 추천 영역 -->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
      <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <!-- 질문 영역 -->

      <div class="card">
        <div class=" card-body">
          <div class="card-text">
            {% autoescape off %}{{ question.content }}{% endautoescape %}
            <!-- {{ question.content|mark }} -->
          </div>
          <div class="d-flex justify-content-end">
    
            <div class="badge badge-primary p-2">
              <div class="mb-2">
                <img class="avatar" src="https://randomuser.me/api/portraits/men/{{question.author.id}}.jpg"/>
                {{ question.author.username }}
              </div>
              <div>
                <i class="fa-regular fa-clock"></i>
                {{ question.create_date }}
              </div>
            </div>
          </div>
        </div>
        {% if request.user == question.author %}
          <div class="my-3">
            <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary text-danger" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
          </div>
        {% endif %}
      </div>
    
      {% include 'pybo/comment_question.html' %}
    

    </div>
  </div>



  {% include 'pybo/answer_list.html' %}

  {% include 'pybo/answer_create_form.html' %}

  <a href="{% url 'pybo:index' %}">목록보기</a>

{% endblock content %}

{% block script %}
  <script>
    $(document).ready(function () {
      let btns = ($('.delete')); // 변수 선언 키워드 let
      btns.on('click', function () {
        console.log('click 발생');
        let answer = confirm('정말 삭제할까요?');
        if (answer) {
          location.href = ($(this).data('uri'))
        } //console.log($(this).data('uri'))
      });

      $('.recommend').on('click', function() {
        if (confirm('정말로 추천하시겠습니까?')) {
          location.href = $(this).data('uri');
        }
      });


      console.log('click 이벤트 핸들러 등록 완료')
    });

  </script>
{% endblock script %}
{% comment %} 도큐먼트를 관리하는 j쿼리 객체를 만들어라.
도큐먼트 = 브라우저 자체를 말한다.
준비가 다 되었으면(ready) 이 함수를(function(){}) 실행시켜라 {% endcomment %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'summernote-bs4.min.css' %}">
{% endblock style %}

{% block script %}
  <script src="{% static 'summernote-bs4.min.js' %}"></script>
  <script src="{% static 'summernote-ko-KR.min.js' %}"></script>
  <script>
    $(function () {
      // Summernote
      $('#id_content').summernote({
        height: 300
      })
    })
  </script>
{% endblock script %}

{% block content %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">
      <i class="fa-regular fa-pen-to-square"></i>
      질문등록
    </h5>
    <form method="post" class="post-form my-3">
      {% csrf_token %}

      {% bootstrap_form form %}
      {% comment %} 
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
              <strong>{{ field.label }}</strong>
              {{ field.errors }}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      <div class="form-group">
        <label for="subject">제목:</label>
        <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        {% if form.content.errors %}
          <div class="text-danger">
            {% for error in form.content.errors %}
              <div>
                <i class="fa-solid fa-triangle-exclamation"></i>
                {{error}}
              </div>
            {% endfor %}
          </div>
        {% endif %}
      </div>
      <div class="form-group">
        <label for="content">내용:</label>
        <textarea class="form-control" name="content" id="content" row="10">{{ form.content.value|default_if_none:'' }}</textarea>
        {% if form.content.errors %}
          <div class="text-danger">
            {% for error in form.content.errors %}
              <div>
                <i class="fa-solid fa-triangle-exclamation"></i>
                {{error}}
              </div>
            {% endfor %}
          </div>
        {% endif %}
      </div> 
      {% endcomment %}

      <button type="submit" class="btn btn-primary">
        <i class="fa-solid fa-check"></i>저장하기
      </button>
      <a href="{% url 'pybo:index' %}" class="btn btn-secondary">
        <i class="fa-solid fa-arrow-left"></i>
        목록보기
      </a>
    </form>
  </div>

{% endblock content %}