common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # url은 common/login/ 이 된다.
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views


urlpatterns =[
    path('', base_views.index, name='index'),    # '/' 에 해당되는 path
    path("admin/", admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls'))
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),                          # 목록 보기
    path('<int:question_id>/', base_views.detail, name='detail'),       # 상세 보기

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.db.models import Q, Count



def index(request):
    """
    pybo 목록출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')    # 정렬 기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:   # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회
    # question_list = Question.objects.order_by('-create_date') #전체 목록
    # question_list = Question.objects.order_by('-author__username') # 이름순으로 검색

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |      # 제목 검색
            Q(content__icontains=kw) |      # 내용 검색
            Q(author__username__icontains=kw) |     # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)   # 답글 글쓴이 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)    # 페이지당 10개씩 보여주기. question_list => 전체목록
    page_obj = paginator.get_page(page)

    context = {
        'kw': kw,
        'page': page,
        'so': so,
        'question_list': page_obj
        }

    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)


    # question.answer_set.create(content=request.POST.get('content'),
    #             create_date=timezone.now())

    # return redirect('pybo:detail', question_id=question_id)
    # print(request.method)
    # print(request.GET)      # dict
    # print(request.POST)     # dict

    # content = request.POST['content']           # 1) 키가 없으면, 예외 발생
    # print('[content]', content)

    # content = request.POST.get('content', '')       # 2) 키가 없으면, None 리턴


    # print('get(content)', content)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pybo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% block style %}{% endblock style %}
  </head>

  <body>
    {% include 'navbar.html' %}
    <div class="container my-3">
      {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block script %}{% endblock script %}

  </body>

</html>

templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}

  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
{% load pybo_filter %}

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item ">
          <a class="nav-link" href="#">
            {% avatar user.id %}
            {% comment %} <img class="avatar" src="https://randomuser.me/api/portraits/men/{{user.id}}.jpg"/> {% endcomment %}
            {% comment %} <img src="http://cdn.edujin.co.kr/news/photo/202105/35768_68227_247.jpg"/ class="avatar"> {% endcomment %}
            {{ user.username }}
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'common:logout' %}">
            <i class="fa-solid fa-arrow-right-from-bracket"></i>
            로그아웃
          </a>
        </li>
      {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">
          <i class="fa-solid fa-arrow-right-to-bracket"></i>
          로그인
        </a>
        <a class="nav-link" href="{% url 'common:signup' %}">
          <i class="fa-solid fa-user-plus"></i>
          회원가입
        </a>
      {% endif %}
    </li>
  </ul>

</div>
</nav>